batch_size: 32
fft_length: 384
frame_length: 256
frame_step: 160
input_shape:
- 389
- 193
learning_rate: 0.0005
max_spectrogram_length: 389
max_text_length: 3
model_path: sound_to_text\202312171725
train_epochs: 100
train_workers: 4
vocab: 'abcdefghijklmnopqrstuvwxyz''?! '
